#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.19
#  in conjunction with Tcl version 8.6
#    Jan 30, 2019 03:44:49 PM IST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import gui_number_addition_prog_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    gui_number_addition_prog_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    gui_number_addition_prog_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#ececec' # Closest X11 color: 'gray92' 
        font10 = "-family {Segoe UI} -size 14 -weight bold -slant "  \
            "roman -underline 0 -overstrike 0"
        font9 = "-family {Segoe UI} -size 17 -weight bold -slant "  \
            "italic -underline 0 -overstrike 0"

        top.geometry("600x450+353+197")
        top.title("New Toplevel")
        top.configure(background="#d9d9d9")
        self.top=top

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.2, rely=0.067, height=61, width=364)
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font=font9)
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(text='''Number Addition Program''')
        self.Label1.configure(width=364)

        self.Label2 = tk.Label(top)
        self.Label2.place(relx=0.067, rely=0.289, height=21, width=124)
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font=font10)
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(text='''Fisrt no. :''')
        self.Label2.configure(width=124)

        self.efno = tk.Entry(top)
        self.efno.place(relx=0.317, rely=0.289,height=20, relwidth=0.423)
        self.efno.configure(background="white")
        self.efno.configure(disabledforeground="#a3a3a3")
        self.efno.configure(font="TkFixedFont")
        self.efno.configure(foreground="#000000")
        self.efno.configure(insertbackground="black")
        self.efno.configure(width=254)

        self.Label3 = tk.Label(top)
        self.Label3.place(relx=0.05, rely=0.422, height=21, width=114)
        self.Label3.configure(background="#d9d9d9")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(font=font10)
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(text='''Second no. :''')
        self.Label3.configure(width=114)

        self.esno = tk.Entry(top)
        self.esno.place(relx=0.317, rely=0.422,height=20, relwidth=0.423)
        self.esno.configure(background="white")
        self.esno.configure(disabledforeground="#a3a3a3")
        self.esno.configure(font="TkFixedFont")
        self.esno.configure(foreground="#000000")
        self.esno.configure(insertbackground="black")
        self.esno.configure(width=254)

        self.Label4 = tk.Label(top)
        self.Label4.place(relx=0.1, rely=0.556, height=21, width=94)
        self.Label4.configure(background="#d9d9d9")
        self.Label4.configure(disabledforeground="#a3a3a3")
        self.Label4.configure(font=font10)
        self.Label4.configure(foreground="#000000")
        self.Label4.configure(text='''Reault :''')
        self.Label4.configure(width=94)

        self.eresult = tk.Entry(top)
        self.eresult.place(relx=0.317, rely=0.556,height=20, relwidth=0.423)
        self.eresult.configure(background="white")
        self.eresult.configure(disabledforeground="#a3a3a3")
        self.eresult.configure(font="TkFixedFont")
        self.eresult.configure(foreground="#000000")
        self.eresult.configure(insertbackground="black")
        self.eresult.configure(width=254)

        self.btnadd = tk.Button(top)
        self.btnadd.place(relx=0.317, rely=0.689, height=24, width=77)
        self.btnadd.configure(activebackground="#ececec")
        self.btnadd.configure(activeforeground="#000000")
        self.btnadd.configure(background="#d9d9d9")
        self.btnadd.configure(disabledforeground="#a3a3a3")
        self.btnadd.configure(foreground="#000000")
        self.btnadd.configure(highlightbackground="#d9d9d9")
        self.btnadd.configure(highlightcolor="black")
        self.btnadd.configure(pady="0")
        self.btnadd.configure(text='''Add''')
        self.btnadd.configure(width=77)

        self.btnclear = tk.Button(top)
        self.btnclear.place(relx=0.467, rely=0.689, height=24, width=77)
        self.btnclear.configure(activebackground="#ececec")
        self.btnclear.configure(activeforeground="#000000")
        self.btnclear.configure(background="#d9d9d9")
        self.btnclear.configure(disabledforeground="#a3a3a3")
        self.btnclear.configure(foreground="#000000")
        self.btnclear.configure(highlightbackground="#d9d9d9")
        self.btnclear.configure(highlightcolor="black")
        self.btnclear.configure(pady="0")
        self.btnclear.configure(text='''Clear''')
        self.btnclear.configure(width=77)

        self.btnquit = tk.Button(top)
        self.btnquit.place(relx=0.617, rely=0.689, height=24, width=77)
        self.btnquit.configure(activebackground="#ececec")
        self.btnquit.configure(activeforeground="#000000")
        self.btnquit.configure(background="#d9d9d9")
        self.btnquit.configure(disabledforeground="#a3a3a3")
        self.btnquit.configure(foreground="#000000")
        self.btnquit.configure(highlightbackground="#d9d9d9")
        self.btnquit.configure(highlightcolor="black")
        self.btnquit.configure(pady="0")
        self.btnquit.configure(text='''Quit''')
        self.btnquit.configure(width=77)

    def set_ui(self):
        self.btnadd.config(command=addit)
        self.btnclear.config(command=clearit)
        self.btnquit.config(command=finishit)

    def finishit(self):
        self.top.exit(0)

    def addit(self):
        a = self.efno.get()
        b = self.esno.get()
        c = int(a) + int(b)
        self.eresult.insert(END,c)

    def clearit(self):
        self.efno.delete(0, tk.END)
        self.esno.delete(0, tk.END)
        self.efno.focus()
if __name__ == '__main__':
    vp_start_gui()





